// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Employee struct {
	EmployeeID  uuid.UUID      `json:"employee_id"`
	FirstName   string         `json:"first_name"`
	LastName    string         `json:"last_name"`
	Email       string         `json:"email"`
	PhoneNumber sql.NullString `json:"phone_number"`
	HireDate    sql.NullTime   `json:"hire_date"`
	Position    sql.NullString `json:"position"`
	Salary      sql.NullString `json:"salary"`
	UserID      uuid.NullUUID  `json:"user_id"`
}

type Material struct {
	MaterialID   uuid.UUID      `json:"material_id"`
	MaterialName string         `json:"material_name"`
	Quantity     sql.NullInt32  `json:"quantity"`
	Unit         sql.NullInt32  `json:"unit"`
	CostPerUnit  sql.NullString `json:"cost_per_unit"`
	ProjectID    uuid.NullUUID  `json:"project_id"`
	Status       sql.NullString `json:"status"`
}

type Project struct {
	ID          uuid.UUID      `json:"id"`
	ProjectName string         `json:"project_name"`
	StartDate   sql.NullTime   `json:"start_date"`
	EndDate     sql.NullTime   `json:"end_date"`
	Budget      sql.NullString `json:"budget"`
}

type Task struct {
	TaskID      uuid.UUID      `json:"task_id"`
	TaskName    string         `json:"task_name"`
	Description sql.NullString `json:"description"`
	StartDate   sql.NullTime   `json:"start_date"`
	EndDate     sql.NullTime   `json:"end_date"`
	ProjectID   uuid.NullUUID  `json:"project_id"`
	EmployeeID  uuid.NullUUID  `json:"employee_id"`
	Status      sql.NullString `json:"status"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	FirstName    string    `json:"first_name"`
	LastName     string    `json:"last_name"`
	Email        string    `json:"email"`
	HashPassword string    `json:"hash_password"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
